# Default values for strategyexecutor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
  
cronJob:
  enabled: true
  image: rg.fr-par.scw.cloud/comentarismoregistry/strategyexecutor_cmd
  tag: latest
  cmd_name: ohlcv_crypto
  schedule: "*/1 * * * *"  # Run every X minutes
  concurrencyPolicy: Forbid
  args: ["ohlcv_crypto"]
  restartPolicy: OnFailure
  env:
    LOG_LEVEL: debug
    DURATION: 1m
    AUTO_MODE: true
    SYMBOL: BTC
    QUOTE: USDT
    LIMIT: 1000
  envsec:
    DATABASE_URL_MAIN: DATABASE_URL_MAIN