# Default values for strategyexecutor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

cronJob:
  enabled: true
  image: rg.fr-par.scw.cloud/comentarismoregistry/strategyexecutor_cmd
  tag: latest
  cmd_name: tvnews
  schedule: "0 */12 * * *"  # 00:00, 12:00 every day
  concurrencyPolicy: Forbid
  args: [ "tvnews" ]
  restartPolicy: OnFailure
  env:
    LOG_LEVEL: debug
  envsec:
    DATABASE_URL_MAIN: DATABASE_URL_MAIN
    DATABASE_URL_READONLY: DATABASE_URL_READONLY
