# Default values for strategyexecutor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

cronJob:
  enabled: true
  image: rg.fr-par.scw.cloud/comentarismoregistry/strategyexecutor_cmd
  tag: latest
  cmd_name: strategyexecutor-hydra-tom
  schedule: "*/1 * * * *"  # Run every X minutes
  concurrencyPolicy: Forbid
  args: ["executor"]
  restartPolicy: OnFailure
  env:
    TARGET_EXCHANGE: hydra
    TARGET_SYMBOL: BTCUSD
    USER_ID: hydra-tom
    LOG_LEVEL: debug
    HYDRA_INSTRUMENT_ID: 9910
    HYDRA_SYMBOL: BTC/USD.crypto
    HYDRA_QTD: 0.001
    HYDRA_SL_PERCENT: 5
  envsec:
    DATABASE_URL_MAIN: DATABASE_URL_MAIN
    DATABASE_URL_READONLY: DATABASE_URL_READONLY
    EXCHANGE_CREDENTIALS_KEY: EXCHANGE_CREDENTIALS_KEY
